-- Outbound webhooks (spec §21.4-21.6, E11 Task 4, AUT-011 delivery half / AUT-012). Three tables plus
-- a rider on 000001's events table. All CREATE/ALTER ... IF NOT EXISTS, so the whole chain stays
-- re-runnable (the 000016/000018 pattern).
--
-- CURSOR DESIGN (fork d.1 — decided): the delivery pump must fan a DURABLE, ORDERED slice of the
-- journal out to each endpoint, but 000001's events table has only a per-session `seq` (UNIQUE per
-- session_id) and a TEXT id — NO global monotonic cursor. §21.4 endpoint filters subscribe to the
-- §21.3 taxonomy (run/attempt/tool_call/workspace/... events), which live in the FULL events journal,
-- so the §24.5 outbox (aggregate-transition topics only — a strict subset) cannot serve them. We
-- therefore add a global monotonic cursor to events directly: an IDENTITY rider, modeled on the E10
-- 000018 ALTER-rider precedent. Fan-out is on-read (the pump scans events past each endpoint's cursor);
-- no journal writer is touched (fan-out-on-write was rejected). Per-endpoint durable progress is the
-- cursor_journal_id column on webhook_endpoints; delivery idempotency is UNIQUE(endpoint_id, event_id),
-- so a re-scan (e.g. after a pump crash, or to catch a late-committing lower id) can never double-emit.
--
-- LATE-COMMIT RECOVERY: an IDENTITY value is assigned at INSERT, but commit order is not id order under
-- concurrency, so a cursor advanced past id N could skip a lower id that committed after N. The pump
-- therefore RE-READS a bounded window back past each endpoint's cursor every tick (cursor - journalLag)
-- and relies on the UNIQUE(endpoint_id, event_id) ON CONFLICT DO NOTHING dedupe to make the re-scan a
-- no-op for already-delivered events — so a late lower-id commit within the window is still delivered.
-- A brand-new endpoint's cursor is initialized to the current max(journal_id) + journalLag in
-- CreateWebhookEndpoint, so it receives only events journaled AFTER it existed, never the whole history.
-- CEILING: journalLag must exceed the max id-gap accrued during one uncommitted append txn; a
-- pg_current_snapshot() xmin low-watermark (or a set-based INSERT...SELECT fan-out) is the upgrade path
-- that removes the heuristic and the re-scan overhead if the journal write-rate grows.

ALTER TABLE events
    ADD COLUMN IF NOT EXISTS journal_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS events_journal_id_idx ON events (journal_id);

-- A registered outbound endpoint (spec §21.4). The signing secrets are SecretRef-ready handles, not
-- plaintext: the pump resolves them through the LP file-secret bridge at delivery time (the E09
-- credential-broker hand-off pattern), and E13 seals them at rest — this task claims NO encryption.
-- Two refs carry a rotation overlap. allow_private_destination is the §21.4 self-host egress allowlist
-- flag (the policy resource proper is E13; this task ships default-deny + an explicit flag).
CREATE TABLE IF NOT EXISTS webhook_endpoints (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    url TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    event_filter TEXT[] NOT NULL DEFAULT '{}',
    api_revision TEXT NOT NULL DEFAULT '',
    signing_secret_ref TEXT NOT NULL DEFAULT '',
    signing_secret_ref_next TEXT NOT NULL DEFAULT '',
    fixed_headers JSONB NOT NULL DEFAULT '{}'::jsonb,
    timeout_ms INTEGER NOT NULL DEFAULT 10000 CHECK (timeout_ms > 0),
    max_attempts INTEGER NOT NULL DEFAULT 20 CHECK (max_attempts > 0),
    retry_window_seconds INTEGER NOT NULL DEFAULT 259200 CHECK (retry_window_seconds > 0),
    allow_private_destination BOOLEAN NOT NULL DEFAULT false,
    cursor_journal_id BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    FOREIGN KEY (organization_id, project_id) REFERENCES projects (organization_id, id)
);

CREATE INDEX IF NOT EXISTS webhook_endpoints_project_idx
    ON webhook_endpoints (organization_id, project_id) WHERE enabled;

-- One delivery per (endpoint, source event). The payload is the exact body captured at fan-out and is
-- immutable, so an operator redelivery replays the SAME id + payload (spec §21.6). next_attempt_at is
-- the backoff clock the pump tick scans (no separate scheduler — the T3 PG-timer idiom, independent
-- code). first_attempt_at anchors the 72h window.
CREATE TABLE IF NOT EXISTS webhook_deliveries (
    id TEXT PRIMARY KEY,
    organization_id TEXT NOT NULL,
    project_id TEXT NOT NULL,
    endpoint_id TEXT NOT NULL REFERENCES webhook_endpoints (id) ON DELETE CASCADE,
    session_id TEXT NOT NULL,
    event_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    state TEXT NOT NULL DEFAULT 'pending'
        CHECK (state IN ('pending', 'delivered', 'dead')),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    first_attempt_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    FOREIGN KEY (organization_id, project_id) REFERENCES projects (organization_id, id),
    UNIQUE (endpoint_id, event_id)
);

CREATE INDEX IF NOT EXISTS webhook_deliveries_due_idx
    ON webhook_deliveries (next_attempt_at) WHERE state = 'pending';

-- One row per HTTP attempt, sanitized (spec §21.6): status, duration, and a bounded response excerpt —
-- and NEVER the signing secret or a secret-ref header value. status_code 0 marks a transport error.
CREATE TABLE IF NOT EXISTS delivery_attempts (
    id BIGSERIAL PRIMARY KEY,
    delivery_id TEXT NOT NULL REFERENCES webhook_deliveries (id) ON DELETE CASCADE,
    attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),
    status_code INTEGER NOT NULL DEFAULT 0,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    response_excerpt TEXT NOT NULL DEFAULT '',
    error TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (delivery_id, attempt_number)
);

-- DML-grant the new tables to the application role (000001's blanket GRANT covered only the tables that
-- existed then); re-grant sequence usage so the delivery_attempts BIGSERIAL and the events IDENTITY are
-- insertable by palai_app (the 000008/000017 pattern).
GRANT SELECT, INSERT, UPDATE, DELETE ON webhook_endpoints, webhook_deliveries, delivery_attempts TO palai_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO palai_app;

INSERT INTO schema_migrations (version) VALUES (20) ON CONFLICT DO NOTHING;
