-- 000049 (usage series): ONE index, so that GET /v1/usage/series is a bucketed aggregate rather than a
-- sequential walk of a tenant's whole ledger. Nothing else — no column, no table. The series is a
-- different READ of rows usage_ledger has carried since 000032, and a new column would be a second
-- writer for a number the ledger already settles exactly once.
--
-- NUMBERING: 000048 (session list) was head when this was written. Two other branches were in flight;
-- if either lands a 000049 first, this file renumbers — the integrator's rule, not a merge conflict.
--
-- ---------------------------------------------------------------------------------------------------
-- WHY AN INDEX AT ALL, MEASURED
-- ---------------------------------------------------------------------------------------------------
--
-- The live stack's own ledger holds 187 rows (`SELECT count(*) FROM usage_ledger` -> 187, 2026-07-31),
-- which is far too small to plan against: at that size Postgres correctly prefers a sequential scan and
-- ANY index measurement would be noise. So the measurement was taken on a seeded copy of the table's
-- exact shape and its three shipped indexes -- 500,000 rows over 20 organizations x 5 projects x 4
-- meters x 90 days, tenants interleaved (a real ledger appends tenants in arrival order, so one
-- tenant's rows are scattered across the heap, which is what makes the heap fetches expensive):
--
--   docker exec palai-<id>-postgres-1 psql -U palai -d postgres -c 'CREATE DATABASE usage_bench;'
--   -- table + the 3 shipped indexes + 500k rows via generate_series, then VACUUM ANALYZE
--   EXPLAIN (ANALYZE, BUFFERS, COSTS OFF) <the UsageSeries query, params inlined>
--
-- Three caller shapes, third of three warm runs (2026-07-31):
--
--   shape                                   BEFORE (3 shipped idx)      AFTER (this index)
--   A  project-scoped, hour, 7-day window   56.024 ms  buffers 5042     7.602 ms  buffers  54
--   B  org-scoped,     hour, 7-day window   70.402 ms  buffers 7802    18.041 ms  buffers 238
--   C  project-scoped, day,  92-day window  55.813 ms  buffers 5042     4.173 ms  buffers  54
--
-- A and C are the two widest windows the API will accept for their bucket; B is the same window read by
-- an org-scoped key, where the project predicate degenerates to TRUE and the scan widens to every
-- project in the organization. The BEFORE plan is a Bitmap Heap Scan whose cost is not FINDING the rows
-- -- the Bitmap Index Scan itself took 1.101 ms of A's 56 -- but the 5000 scattered heap blocks it then
-- fetches. AFTER, every plan is an Index Only Scan with `Heap Fetches: 0`.
--
-- WHY THE EXISTING THREE DO NOT SERVE IT, each for its own reason:
--
--   usage_ledger_tenant_meter_idx (organization_id, project_id, meter, occurred_at DESC)
--     `meter` sits BETWEEN the tenant equality and the time range. The series query constrains no
--     meter (that is the point -- it returns every meter's line), so occurred_at is not a leading-edge
--     boundary and the index degrades to finding the tenant's rows and filtering. It is still the index
--     the planner picks for shape A, and it still costs 5042 buffers.
--   usage_ledger_tenant_keyset_idx (organization_id, occurred_at DESC, id DESC)
--     Serves the org-scoped shape B's boundary well and is duly chosen there, but carries no
--     project_id, so a project-scoped caller filters after the fact, and carries neither meter nor
--     quantity, so every row is still a heap fetch.
--   usage_ledger_session_idx (organization_id, project_id, session_id, meter)   [000048]
--     Keyed on session. It cannot answer a time window at all.
--
-- WHY IT IS COVERING, which is the whole 7x. A plain btree on (organization_id, project_id,
-- occurred_at) was measured too and is NOT worth a migration: shape A went 56.024 ms / 5042 buffers ->
-- 75.384 ms / 5031 buffers. It finds the rows fractionally faster and then does the identical 5000 heap
-- fetches, which were always the cost. Adding meter, unit and quantity as INCLUDE payload is what makes
-- the scan index-only and takes the buffers to 54. The INCLUDE columns are payload, not key columns:
-- they widen the leaf entries without deepening the tree or constraining the sort order.
--
-- COST HONESTLY STATED: this is a fourth index on an append-only table, so every settlement INSERT now
-- maintains four. The ledger's write path is one row per model step inside a transaction that is
-- already writing the model request, the fold state and an event, so the marginal write is small -- but
-- it is not zero, and it is the price of the read above.
CREATE INDEX IF NOT EXISTS usage_ledger_tenant_series_idx
    ON usage_ledger (organization_id, project_id, occurred_at)
    INCLUDE (meter, unit, quantity);

-- No grant and no policy call: usage_ledger already carries 000032's REVOKE-narrowed grants and 000029's
-- tenant policy, and an index is an object on an existing table that inherits both. 000032 re-asserts
-- its REVOKE on every boot and runs LAST, so nothing here can widen what palai_app may do to the table.

INSERT INTO schema_migrations (version) VALUES (49) ON CONFLICT DO NOTHING;
