-- The run's RUN-SPECIFIC INSTRUCTIONS (spec §25.12 layer 5): the `instructions` string the create
-- request carried, stored on the run so the execution path can actually apply it.
--
-- WHAT WAS WRONG. `instructions` has been in the published response-create schema for the life of
-- that schema, and measured against a real provider on 2026-08-01 it reached the model as NOTHING:
-- the same input with a 320-word `instructions` and with none both measured usage.input_tokens 48.
-- The field was accepted, folded into the idempotency hash, and dropped. Nothing stored it, so
-- nothing could have applied it.
--
-- WHY IT IS ON THE RUN. The reader is model dispatch, once per model step, and it does not hold the
-- request body — the same reason `delegation` (000007) and `output_contract` (000054) are columns on
-- this table rather than re-derived per reader. Re-deriving per step is also how two steps of one run
-- come to disagree about what the model was told.
--
-- WHY TEXT AND NOT JSONB. This is one caller-supplied string, not a document: it is placed verbatim
-- as a system turn and never indexed, queried into, or partially read. `output_contract` is JSONB
-- because it IS a document that gets validated against. NULL means the request named no instructions
-- — every run created before this migration and every run that does not opt in — so an
-- instruction-free run's row and its provider request stay bit-identical.
--
-- The PINNED REVISION's instructions (§25.12 layer 3) are deliberately NOT copied here. They already
-- live on agent_revisions.instructions, written by agent CRUD since E11, and the run pins the
-- revision immutably (AGT-001), so reading them through the pin is what keeps an old run
-- reproducible. Copying them onto the run would create a second source of truth for a value that
-- already has one. What was missing there was never storage — it was that PinnedRunConfig did not
-- SELECT the column.
--
-- Only ALTER TABLE ADD COLUMN IF NOT EXISTS on a table 000001 created, so no new grants are needed
-- and the chain stays safe to re-run (Migrate is idempotent).
ALTER TABLE runs ADD COLUMN IF NOT EXISTS instructions TEXT;

INSERT INTO schema_migrations (version) VALUES (55) ON CONFLICT DO NOTHING;
