-- Reverse of 000001_core.up.sql. CASCADE takes the terminal-run trigger down with `runs` and the six
-- owned sequences down with their tables; dropping every table first clears the palai_app grants, so the
-- role can be removed and an up -> down -> up reapply stays clean.

DROP TABLE IF EXISTS
    a2a_interfaces,
    a2a_remote_agents,
    a2a_task_refs,
    agent_profiles,
    agent_revisions,
    api_keys,
    approvals,
    artifacts,
    attempts,
    audit_events,
    background_tasks,
    budgets,
    capability_jobs,
    capability_workers,
    changeset_findings,
    changesets,
    checkpoints,
    chunk_revisions,
    commands,
    config_revisions,
    delivered_messages,
    delivery_attempts,
    deployment_desired,
    document_revisions,
    durable_jobs,
    environment_values,
    environments,
    events,
    hooks,
    host_quarantine,
    idempotency_records,
    inbox,
    index_revisions,
    ingestion_jobs,
    integration_bots,
    job_attempts,
    knowledge_bases,
    knowledge_sources,
    mcp_connections,
    merge_records,
    messages,
    model_connections,
    model_requests,
    model_route_revisions,
    model_routes,
    outbox,
    preparation_receipts,
    principals,
    projects,
    publications,
    queue_connections,
    queue_deliveries,
    queue_effect_receipts,
    queue_messages,
    quotas,
    remote_tool_operations,
    repository_bindings,
    responses,
    run_template_revisions,
    runner_enrollments,
    runner_leases,
    runner_pool_keys,
    runner_pools,
    runners,
    runs,
    schedule_occurrences,
    schedules,
    schema_migrations,
    schema_revisions,
    secret_refs,
    session_sequences,
    sessions,
    skill_revisions,
    skills,
    slack_approval_deliveries,
    slack_connections,
    slack_message_turns,
    slack_reply_deliveries,
    slack_thread_sessions,
    tasks,
    tool_calls,
    tool_revisions,
    tool_set_revisions,
    tools,
    transcript_boundaries,
    trigger_deliveries,
    trigger_revisions,
    triggers,
    usage_ledger,
    webhook_deliveries,
    webhook_endpoints,
    workspace_allocations,
    workspace_leases,
    workspace_snapshots,
    workspaces
CASCADE;

DROP FUNCTION IF EXISTS enforce_run_terminal_final();

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'palai_app') THEN
        EXECUTE 'DROP OWNED BY palai_app';
        DROP ROLE palai_app;
    END IF;
END
$$;
